# Generated by Django 4.2.5 on 2024-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100, unique=True, verbose_name='Coupon Code')),
                ('discount_rate', models.PositiveIntegerField(verbose_name='Discount Rate')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
            ],
        ),
    ]
