# Generated by Django 4.2.5 on 2024-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_code', models.CharField(max_length=100, unique=True, verbose_name='Combo Code')),
                ('combo_name', models.CharField(max_length=255, verbose_name='Combo Name')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('products', models.ManyToManyField(related_name='combos', to='Food.food', verbose_name='Products')),
            ],
        ),
    ]
