# Generated by Django 4.2.5 on 2024-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True, verbose_name='Product Code')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
