# Generated by Django 4.2.5 on 2024-07-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Combo', '0001_initial'),
        ('Food', '0003_alter_food_image'),
        ('Order', '0003_rename_coupon_code_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Combo.combo', verbose_name='Combo')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.food', verbose_name='Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order', verbose_name='Order')),
            ],
        ),
    ]
