# Generated by Django 4.2.5 on 2024-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_detailorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
