# Generated by Django 4.2.5 on 2024-07-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
